name: Hostinger Deploy

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd domains/demopreview.in/public_html/coolingpoint
            git reset --hard
            git pull https://${{ secrets.SECRET_PAT }}@github.com/dkpankaj1/CoolTechSolutions.git dev
            git checkout dev
            curl -sS https://getcomposer.org/installer | php
            php composer.phar update --optimize-autoloader
            php artisan migrate:fresh --seed --force
            rm composer.phar
